import Head from "next/head";
//
import { AnimatePresence } from "framer-motion";
import AnimatedPage from "../../main-site/components/animations/animatedpage";
import Navigation from "../../main-site/components/navigation/navigation.component";
import Footer from "../../main-site/components/footer/footer.component";
import Scripts from "../../main-site/routes/scripts/scripts.component";
import FI from "../../main-site/components/floatingicon/fi.component";
import { hostname } from "../../config/hostname";

import styles from "../../styles/mainpage.module.scss";

export async function getServerSideProps(context) {
  const id = context.params.id;
  const res = await fetch(`${hostname}/api/scripts/${id}`);
  const script = await res.json();
  const res2 = await fetch(`${hostname}/api/scripts`);
  const allscripts = await res2.json();
  return {
    props: { script, allscripts, id },
  };
}

const ScriptsPage = ({ script, allscripts, id }) => {
  return (
    <div className={styles["mainsite-bg"]}>
      <Head>
        <title>Scripthome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AnimatePresence mode="wait">
        <Navigation key={1} />
        <FI />
        <AnimatedPage key={2}>
          <Scripts script={script} allscripts={allscripts} />
          <Footer />
        </AnimatedPage>
      </AnimatePresence>
    </div>
  );
};

export default ScriptsPage;
