import Head from "next/head";
import { AnimatePresence } from "framer-motion";
import AnimatedPage from "../../main-site/components/animations/animatedpage";
import Navigation from "../../main-site/components/navigation/navigation.component";
import Footer from "../../main-site/components/footer/footer.component";
import FI from "../../main-site/components/floatingicon/fi.component";
import { hostname } from "../../config/hostname";
import axios from "axios";
import Adduser from "../../main-site/routes/uploaduser/adduser.route";
import { useContext, useEffect, useState } from "react";
import { AllScriptContext } from "../../main-site/contexts/allscripts/scripts.context";

import styles from "../../styles/mainpage.module.scss";

export async function getServerSideProps(context) {
  const slug = context.params.slug;
  const res = await axios({
    url: `${hostname}/api/getuserbyname/${slug}`,
    method: "get",
  });
  if (res.data.exists) {
    const userdata = res.data.user;
    const exists = true;
    return {
      props: { userdata, exists },
    };
  } else {
    const exists = false;
    return {
      props: { exists },
    };
  }
}

const AddUserPage = ({ userdata, exists }) => {
  const [userscripts, setUS] = useState([]);
  const { scripts } = useContext(AllScriptContext);
  useEffect(() => {
    if (!exists) {
      alert("User does not exist!");
    } else {
      setUS(
        scripts.filter((script) => {
          return script.user_id === userdata.id;
        })
      );
    }
  }, [exists, scripts, userdata]);

  return (
    <div className={styles["mainsite-bg"]}>
      <Head>
        <title>Scripthome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {exists ? (
        <AnimatePresence mode="wait">
          <Navigation key={1} />
          <FI />
          <AnimatedPage key={2}>
            <div className={styles["place-center-t"]}>
              <Adduser userscripts={userscripts} userdata={userdata} />
              <Footer />
            </div>
          </AnimatedPage>
        </AnimatePresence>
      ) : null}
    </div>
  );
};

export default AddUserPage;
