import Head from "next/head";
import { AnimatePresence } from "framer-motion";
import AnimatedPage from "../main-site/components/animations/animatedpage";
import Navigation from "../main-site/components/navigation/navigation.component";
import Footer from "../main-site/components/footer/footer.component";
import Home from "../main-site/routes/home/home.route";
import FI from "../main-site/components/floatingicon/fi.component";

import styles from "../styles/mainpage.module.scss";

export default function HomePage() {
  return (
    <div className={styles["mainsite-bg"]}>
      <Head>
        <title>Scripthome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AnimatePresence mode="wait">
        <Navigation key={1} />
        <FI />
        <AnimatedPage key={2}>
          <Home />
          <Footer />
        </AnimatedPage>
      </AnimatePresence>
    </div>
  );
}
